# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DouyinApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DouyinApp

  target 'DouyinAppUITests' do
    pod 'WebDriverAgentLib', :path => '../../'
  end

end


# Fix Build error:
#Showing All Errors Only
# /Users/user/Desktop/work/git/XCUITest/Pods/CocoaHTTPServer/Core/Mime/MultipartMessageHeaderField.m:45:3: Implicit declaration of function 'LOG_OBJC_MAYBE' is invalid in C99
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', 'DD_LEGACY_MACROS=1']
    end
  end
end
